### GET 减库存请求，未使用锁，会出现超卖问题
GET http://localhost:10010/stock/deductWithoutLock
Accept: application/json

### GET 减库存请求，使用 synchronized 锁，有效解决超卖问题
GET http://localhost:10010/stock/deductWithSynchronizedLock
Accept: application/json

### GET 减库存请求，使用 ReentrantLock 锁，有效解决超卖问题
GET http://localhost:10010/stock/deductWithReentrantLock
Accept: application/json

### GET 减库存请求，基于 MySQL 数据库，未使用锁，会出现超卖问题
GET http://localhost:10010/stock/baseMysqlDeductWithoutLock
Accept: application/json

### GET 减库存请求，基于 MySQL 数据库，使用 synchronized 锁，单例模式下有效解决超卖问题，多例模式下会出现超卖问题
GET http://localhost:10010/stock/baseMysqlDeductWithSynchronizedLock
Accept: application/json

### GET 减库存请求，基于 MySQL 数据库，使用 ReentrantLock 锁，单例模式下有效解决超卖问题，多例模式下会出现超卖问题
GET http://localhost:10010/stock/baseMysqlDeductWithReentrantLock
Accept: application/json

### GET 减库存请求，基于 MySQL 数据库，使用 事务 + synchronized 锁，会出现超卖问题（会失效）
GET http://localhost:10010/stock/transactionalBaseMysqlDeductWithSynchronizedLock
Accept: application/json

### GET 减库存请求，基于 MySQL 数据库，使用 事务 + Reentrant 锁，通过 “读未提交” 隔离级别有效解决超卖问题，但实际项目不推荐
GET http://localhost:10010/stock/transactionalBaseMysqlDeductWithReentrantLock
Accept: application/json

### GET 减库存请求，基于 MySQL 数据库，开启2个实例（一个端口号为10100，一个端口号为10086）作为集群，nginx 做均衡负载，访问端口80，会出现超卖问题（会失效）
GET http://localhost:80/stock/baseMysqlDeductWithSynchronizedLock
Accept: application/json

### GET 减库存请求，基于 MySQL 数据库锁，单例模式，有效解决超卖问题
GET http://localhost:10010/stock/mysqlSingletonPatternDbLock
Accept: application/json

### GET 减库存请求，基于 MySQL 数据库锁，多例模式，有效解决超卖问题
GET http://localhost:10010/stock/mysqlPrototypePatternDbLock
Accept: application/json

### GET 减库存请求，基于 MySQL 数据库锁，事务模式，有效解决超卖问题
GET http://localhost:10010/stock/mysqlTransactionalDbLock
Accept: application/json

### GET 减库存请求，基于 MySQL 数据库锁，开启2个实例（一个端口号为10100，一个端口号为10086）作为集群，nginx 做均衡负载，访问端口80，有效解决超卖问题
GET http://localhost:80/stock/mysqlSingletonPatternDbLock
Accept: application/json

### GET 减库存请求，基于 MySQL 数据库锁，事务模式，使用 SELECT ... FOR UPDATE 悲观锁，有效解决超卖问题
GET http://localhost:10010/stock/mysqlTransactionalDbLockForUpdate
Accept: application/json

### GET 减库存请求，基于乐观锁（非注解模式），有效解决超卖问题
GET http://localhost:10010/stock/optimisticLockStockDeductWithNonAnnotatedVersion
Accept: application/json

### GET 减库存请求，基于乐观锁（注解模式），有效解决超卖问题
GET http://localhost:10010/stock/optimisticLockStockDeductWithAnnotatedVersion
Accept: application/json

### GET 减库存请求，基于乐观锁（注解模式），有效解决超卖问题
GET http://localhost:10010/stock/optimisticLockStockDeductWithTimestamp
Accept: application/json
